Add Volume Mounts
rancher/system-upgrade-controller pull request #195
Opened 2022-04-21 20:19 UTC by luthermonson

Adds VolumeMounts to the ContainerSpec

2022-04-21 21:17 UTC, dweomer commented
As discussed in Slack:

I think what we need here is a new `VolumeSpec` (or `MountSpec` or even `BindSpec`) sub-type, akin to our custom `SecretSpec`, that references a host location/source (i.e. `HostPath` or `Source`) to mount into the containers, e.g.:
```go
type MountSpec struct {
	Name     string `json:"name,omitempty"`
	Path     string `json:"path,omitempty"`
	HostPath string `json:"path,omitempty"`
}
```

---

I need to think about it more to decide if I am comfortable with adding general purpose volumes to plans. :thinking:

2022-04-21 21:20 UTC, dweomer commented on pkg/upgrade/container/container.go
> +
This isn't enough because you can reference volumes by name all day but if they do not exist for the pod ...

2022-04-21 21:21 UTC, dweomer requested changes
As discussed in Slack:

I think what we need here is a new `VolumeSpec` (or `MountSpec` or even `BindSpec`) sub-type, akin to our custom `SecretSpec`, that references a host location/source (i.e. `HostPath` or `Source`) to mount into the containers, e.g.:
```go
type MountSpec struct {
	Name     string `json:"name,omitempty"`
	Path     string `json:"path,omitempty"`
	HostPath string `json:"path,omitempty"`
}
```

You could use such in a plan to give you enough information to specify both the volumes for the pod and the references to such for individual containers (assuming you need to reference them: maybe we just mount any volumes specified for all containers?).

2022-04-21 21:21 UTC, dweomer commented
> As discussed in Slack:
> 
> I think what we need here is a new `VolumeSpec` (or `MountSpec` or even `BindSpec`) sub-type, akin to our custom `SecretSpec`, that references a host location/source (i.e. `HostPath` or `Source`) to mount into the containers, e.g.:
> 
> ```go
> type MountSpec struct {
> 	Name     string `json:"name,omitempty"`
> 	Path     string `json:"path,omitempty"`
> 	HostPath string `json:"path,omitempty"`
> }
> ```
> 
> You could use such in a plan to give you enough information to specify both the volumes for the pod and the references to such for individual containers (assuming you need to reference them: maybe we just mount any volumes specified for all containers?).

I need to think about it more to decide if I am comfortable with adding general purpose volumes to plans. :thinking:

2022-04-22 03:14 UTC, luthermonson commented
ya i agree, there is more to this than just volume mounts... le sigh

2022-04-27 17:33 UTC, dweomer commented on pkg/apis/upgrade.cattle.io/v1/types.go
> +type Volume struct {
```suggestion
type VolumeSpec struct {
```

2022-04-27 17:34 UTC, dweomer commented on pkg/apis/upgrade.cattle.io/v1/types.go
>  }
```suggestion
type VolumeSpec struct {
	Name        string `json:"name,omitempty"`
	Source      string `json:"source,omitempty"`
	Destination string `json:"destination,omitempty"`
}
```

2022-04-27 17:37 UTC, dweomer reviewed
Looks good (minus the nit/suggestion hinting at stylistic divergence).

2022-04-27 18:06 UTC, dweomer commented on pkg/upgrade/job/job.go
> +					Path: v.Source, Type: &hostPathDirectory,
```
					Path: v.Source, Type: &hostPathDirectory,
```

:thinking: I thought that we wanted to leave the type off if we could?

2022-04-27 19:37 UTC, merged