Allow Plan to specify Job deadline
rancher/system-upgrade-controller pull request #244
Opened 2023-06-21 15:24 UTC by connorkuehl

If a workload is known to be slow in excess of the system-upgrade-controller deployment's default deadline, allow the Plan creator to specify a job deadline with the plan so that the entailing job may run to completion.

2023-06-27 19:44 UTC, connorkuehl commented
@brandond Would you be willing to take a look at this?

2023-06-27 20:28 UTC, brandond requested changes
This is great, thanks for the changes and matching tests!

I feel like we should allow the administrator to specify an upper bound on the deadline - perhaps add a `ActiveDeadlineSecondsMax` var wired up to `SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS_MAX`, that (if set) provides an upper bound for the value from the job spec? That gives the cluster administrator an option to cap the user-provided value.

2023-06-27 20:57 UTC, brandond approved these changes

2023-06-27 20:58 UTC, connorkuehl commented
Thanks for the review! :slightly_smiling_face:

2023-06-27 21:10 UTC, briandowns approved these changes

2023-06-27 21:10 UTC, dereknola approved these changes

2023-06-27 23:00 UTC, merged

2023-06-28 20:23 UTC, connorkuehl commented
I'm still learning about the Rancher ecosystem, so at the risk of asking a dumb question: is there a way for me to track when this change is packaged up as part of a [Rancher release](https://github.com/rancher/rancher/releases)?

2023-06-29 00:28 UTC, brandond commented
If there's not an issue to upgrade the version of the SUC used by Rancher's upgrade charts, one will need to be created to track doing so. Standalone users can use the new release whenever they want, of course.