Adding the ability to define a secuirty context and SELinux options
rancher/system-upgrade-controller pull request #257
Opened 2023-08-24 22:51 UTC by Auston-Ivison-Suse

2023-08-24 23:38 UTC, brandond requested changes
Are you going to plumb these new fields through to anything? See how the SecurityContext for the upgrade pod is generated at https://github.com/rancher/system-upgrade-controller/blob/04a0b9ef5858657f20949cd022e58ad19de029df/pkg/upgrade/job/job.go#L326-L333

You need to modify that bit to actually use the SecurityContext from the Plan, if it is non-nil. You also need to similarly wire up the SELinuxOptions.

2023-08-24 23:38 UTC, brandond commented on pkg/apis/upgrade.cattle.io/v1/types.go
> +	Image   string                 				`json:"image,omitempty"`
please `go fmt` this properly; the indentation is unusual.

2023-08-24 23:39 UTC, brandond commented
Also, please fill out the PR body with some background and an example of how and when this might be used.

2023-08-25 18:48 UTC, brandond requested changes
Couple nits on how this is plumbed through to the `upgrade` container.

Note that the `prepare` container also uses all the fields from `ContainerSpec`; we should probably wire up all the SecurityContext stuff there as well. I'm not sure why it currently doesn't do this, as it's not documented as only supported for the upgrade pod.

2023-08-25 18:48 UTC, brandond commented on pkg/upgrade/container/container.go
> +func WithSELinuxOptions(seLinuxoptions *corev1.SELinuxOptions) Option {
I'm not sure this is necessary - you're setting `container.SecurityContext.SELinuxOptions`, when `container.SecurityContext` is already set by the `WithSecurityContext` function. Just set this directly on the SecurityContext.

2023-08-25 18:48 UTC, brandond commented on pkg/apis/upgrade.cattle.io/v1/types.go
> +	SELinuxOptions  *corev1.SELinuxOptions  `json:"seLinuxOptions,omitempty"`
Just realized that SELinuxOptions is actually nested within the SecurityContext struct; we don't need a separate field for it. Is there any specific reason why you wanted to allow setting it separately? I guess I could see the value in allowing use of the default SecurityContext, but just overriding the SELinuxOptions. I could see this being confusing though, as it provides two places to set the SELinuxOptions - both in the SecurityContext's nested field, and in the top-level ContainerSpec field.

2023-08-25 18:48 UTC, brandond commented on pkg/upgrade/job/job.go
> +	}
```suggestion
	if plan.Spec.Upgrade.SELinuxOptions != nil {
		securityContext.SELinuxOptions = plan.Spec.Upgrade.SELinuxOptions
	}
```

2023-08-25 18:48 UTC, brandond commented on pkg/upgrade/job/job.go
> +			upgradectr.WithSELinuxOptions(seLinuxOptions),
```suggestion
```

2023-08-30 17:39 UTC, brandond requested changes
Currently, the option to use a privileged pod for the upgrade pod is set at the controller level:
https://github.com/rancher/system-upgrade-controller/blob/f4a9a0fbe69b144b5b6f6cf69aab5472498211b0/pkg/upgrade/job/job.go#L73-L82

Since this is a security control enforced by the administrator, I feel like we probably also need to wire up a new option to allow administrators to opt in to allowing users to specify a SecurityContext for their pods. The option should default to false, and if it is false the SecurityContext from the Plan should be ignored - perhaps along with a logged warning?

2023-08-30 17:39 UTC, brandond commented on pkg/upgrade/job/job.go
> +
This is redundant. The only way to set the SELinuxOptions is via a non-nil plan.Spec.Upgrade.SecurityContext, which we just assigned into securityContext in the previous check.
```suggestion
```

2023-08-30 17:39 UTC, brandond commented on pkg/upgrade/job/job.go
> +	}
I would probably just express this as:
```suggestion
	var securityContext *corev1.SecurityContext
	if plan.Spec.Upgrade.SecurityContext != nil {
		securityContext = plan.Spec.Upgrade.SecurityContext
	} else {
		securityContext = &corev1.SecurityContext{
			Privileged: &Privileged,
			Capabilities: &corev1.Capabilities{
				Add: []corev1.Capability{
					corev1.Capability("CAP_SYS_BOOT"),
				},
			},
		}
	}
```

2023-09-29 06:18 UTC, brandond commented
@Auston-Ivison-Suse are you still working on this?

2023-10-13 17:41 UTC, brandond commented
You generally want to rebase your branch on top of master, instead of pulling master into your branch. makes for a cleaner commit log.

2023-10-25 20:43 UTC, dweomer approved these changes

2023-11-07 18:32 UTC, brandond approved these changes

2023-11-23 17:53 UTC, merged