feat: Reduce permissions for system-upgrade-controller serviceaccount
rancher/system-upgrade-controller pull request #288
Opened 2024-02-17 22:56 UTC by SISheogorath

This patch drastically cuts down the permissions of the system-upgrades-controller from the previous cluster-admin permissions to a tailored set of permissions for the controller.

2024-02-23 00:21 UTC, dweomer approved these changes
LGTM

2024-02-23 01:52 UTC, SISheogorath commented
Before we merge that, I had one more thought: Currently the controller installs its own CRDs if they aren't present in the cluster. So maybe it needs some more permissions for creating CRDs? (I install them separately as part of the kustomization, so it wasn't a thing for me.)

2024-02-23 23:12 UTC, SISheogorath commented
If it can't read crds directly, it just assumes they exist and assumes it's all fine.

We could include the CRD itself into the kustomize output.

2024-02-28 18:40 UTC, brandond commented
Can you rebase this on top of current master so that CI can finish?

2024-02-28 18:45 UTC, SISheogorath commented
There we go :)

2024-02-28 18:57 UTC, dereknola approved these changes

2024-02-28 19:53 UTC, brandond requested changes
Can you remove the changes to the image/taq kustomization from this PR? I'm not understanding what those have to do with the RBAC; if you want to change that, please open another PR.

2024-02-28 20:09 UTC, SISheogorath commented
They had nothing to do with the change, just cleaning up along the way. Undid them for now :)

2024-02-28 21:28 UTC, merged