Revert "fix(kustomize): Deploy latest system-upgrade-controller"
rancher/system-upgrade-controller pull request #304
Opened 2024-03-27 22:46 UTC by onno204

This reverts commit [4e31e5d6a0926df9f370a06c9ea3250ee1e088b1](https://github.com/rancher/system-upgrade-controller/commit/4e31e5d6a0926df9f370a06c9ea3250ee1e088b1).

This "fixes" issue #302 by reverting the commit that caused the issue.
Currently some installations break because of the missing `latest` tag on the [docker hub](https://hub.docker.com/r/rancher/system-upgrade-controller/tags) as explained by @brandond [here](https://github.com/rancher/system-upgrade-controller/commit/4e31e5d6a0926df9f370a06c9ea3250ee1e088b1#r139564543)

I suggest reverting this PR once a 'latest' tag has been added to the docker hub but for now keep installations working by using a version tag instead of a latest tag.

2024-03-28 00:12 UTC, mysticaltech commented
Super important folks, please fix ASAP, tons of users affected because of this.

2024-09-26 02:11 UTC, brandond requested changes
nit: lets move to use the most recent release.

2024-09-26 02:11 UTC, brandond commented on manifests/system-upgrade-controller.yaml
> +          image: rancher/system-upgrade-controller:v0.11.0
```suggestion
          image: rancher/system-upgrade-controller:v0.14.0
```

2024-09-26 02:11 UTC, brandond commented on kustomization.yaml
> +  newTag: v0.8.0
```suggestion
  newTag: v0.14.0
```

2024-09-26 02:25 UTC, brandond approved these changes

2024-09-26 02:25 UTC, merged