chore: Upgrade kubectl to version 1.30.0
rancher/system-upgrade-controller pull request #310
Opened 2024-05-15 19:04 UTC by SISheogorath

Just a regular upgrade, since 1.25.4 is a bit dated by now. Also making sure we actually used the docker.io image unless explicitly changed.

2024-06-13 11:39 UTC, IT-Cru commented
Does this currently also blocks upgrades to k3s 1.30.x? If yes, would be nice to get it merged :)

2024-06-13 21:24 UTC, SISheogorath commented
I don't think it should have that impact, it's just updates for good measure. But you can validate it the impact on your cluster, if you want. All you need to do is adjusting the environment variable as shown in the manifest.

2024-06-13 21:37 UTC, brandond commented
kubectl is widely compatible with both newer and older versions of the apiserver. Upgrading or not upgrading doesn't block or unblock anything.

2024-08-29 17:04 UTC, brandond requested changes
lgtm, but lets bump this to latest before merging

2024-08-29 17:04 UTC, brandond commented on manifests/system-upgrade-controller.yaml
> +  SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: "docker.io/rancher/kubectl:v1.30.0"
```suggestion
  SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: "docker.io/rancher/kubectl:v1.30.4"
```

2024-08-29 17:04 UTC, brandond commented on pkg/upgrade/job/job.go
> +	defaultKubectlImage            = "docker.io/rancher/kubectl:v1.30.0"
```suggestion
	defaultKubectlImage            = "docker.io/rancher/kubectl:v1.30.4"
```

2024-08-29 17:06 UTC, closed without merging

2024-08-29 17:06 UTC, brandond commented
nm, we actually already bumped these in https://github.com/rancher/system-upgrade-controller/pull/326